### ISSUE TITLE
Bot is sending help notification every few days

### ISSUE THREAD

**Issue by MetalJulien** [franciscod/telegram-twitter-forwarder-bot#9] opened 2016-07-18 14:10 UTC
The bot is sending every few days a notification telling you how to use the bot ("Hey! Use commands to talk with me, please! See /help") even if you already have set it up.

**Comment by AnakTeka** [comment] 2016-07-19 10:35
Don't reply quote the bot on group chat.

**Comment by franciscod** [comment] 2016-08-17 03:31
Yeah, the bot replies with that message whenever you talk to it and it doesn't recognize what you said. Is this happening when you message the bot or is it talking (unintendedly) in another situation?

**Comment by MetalJulien** [comment] 2016-08-17 16:00
Happily, the problem never occurred again. How long does it the bot take to
check for updates? Maybe I used a wrong command some minutes before (if so,
more than 15 minutes before) and this was right at the beginning of an
interval?

2016-08-17 5:31 GMT+02:00 Francisco Demartino <notifications@github.com>:

**Comment by franciscod** [comment] 2016-08-17 16:08
The bot is a bit "crowded" in terms of api rate limits: a lot of people is
using it and sometimes can't update every subscription at the intended
interval. It should have a better scheduling of these requests :)

**Comment by MetalJulien** [comment] 2016-08-17 16:15
Maybe use webhook :) Never used it yet, but would surely help alot
https://core.telegram.org/bots/api#setwebhook

2016-08-17 18:08 GMT+02:00 Francisco Demartino <notifications@github.com>:

**Comment by franciscod** [comment] 2016-08-17 17:17
I think the issue is twitter's rate limit. There is also the possibility of
asking users for tokens so that limit is a bit bigger but I don't like that
option a lot :)

**Comment by franciscod** [comment] 2017-03-01 16:51
closing this since it's a bunch of unrelated things in a single issue

**Closed by franciscod** 2017-03-01 16:51 UTC
